FROM mhart/alpine-node:8

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python build-base

WORKDIR /app
RUN git clone https://github.com/ethereum-alarm-clock/cli.git /app
COPY eacc301fee591a459d572cf1c5daa423f4433785 /app

RUN cd /app
RUN npm install -g npm@latest
RUN npm cache verify
RUN npm install

CMD ["node", "tools/spamTx.js", "--wallet", "eacc301fee591a459d572cf1c5daa423f4433785", "--password", "chronologic", "--repeat", "3", "--recurrent", "300", "--provider", "wss://ropsten.infura.io/ws", "--gasPrice", ".5"]
